### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by Sky-seed0215** [FiboMonBotMaker/CinnamonBot_for-d.py#2]
### main.pyの換装
--------------

- [ TOKENは別ディレクトリの.envから取得。]

**Comment by Sky-seed0215** [comment]
### 対象コミット
------

- [abe8a00](https://github.com/FiboMonBotMaker/CinnamonBot_for-d.py/commit/abe8a008e54e96cd93e747a184341bb354dfb6c2)

**Comment by Sky-seed0215** [comment]
@nikawamikan 
できるようだったらリファクタよろしくお願いします。

**Comment by nikawamikan** [comment]
main.pyは全く問題なさそうでした
